### ISSUE TITLE
SAML Applications dropping Users & Groups if not ignored.

### ISSUE THREAD

**Issue by donmedlinger-cb** [okta/terraform-provider-okta#1702]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
version =  3.34

### Affected Resource(s)

- okta_saml_app
- okta_app_user
- okta_app_group_assignment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Users and Groups assigned to a SAML app via okta_app_user & okta_app_group_assignment should not be dropped if the `okta_saml_app` does not have the users & groups attribute ignored.

#### Can this be done in the Admin UI?
N/A

#### Can this be done in the actual API call?
N/A

### Actual Behavior
Users & Groups are unassigned the application.

### Steps to Reproduce

1. Plan/Apply that does the following:
- SAML App via terraform
- Assigns any user or group to the application via okta_app_user OR okta_app_group_assignment
2. Make no changes to the assignment or application
3. Do a Plan
4. It will say that it's going to remove the users/groups from the Application because they are present on the Imported apps' attributes but not defined on that resource

### References

- #0000

**Comment by exitcode0** [comment]
I believe this was resolved versions >= [v4.0.0](https://github.com/okta/terraform-provider-okta/releases/tag/v4.0.0)

**Comment by cjh-Ella** [comment]
I think this issue also applies to `okta_app_bookmark` resource and is not yet resolved.

We cannot define `users` or `groups` inside the `okta_app_bookmark` resource.

Even if we imported the bookmark app and `okta_app_group_assignment`, when we run `terraform plan`, terraform still thinks that we didn't define `users` or `groups` for the `okta_app_bookmark` resource, and when we run `terraform apply`, it will remove all assignments thought assignments were imported.

Only solution for now would be to ignore the `users` and `groups` argument in the `okta_app_bookmark` resource.

**Comment by monde** [comment]
@donmedlinger-cb @cjh-Ella assigning users and groups directly by an app resource was removed from the Okta terraform provider when we had a major v4 release recently. Please upgrade to the latest version of the Okta TF provider.

**Comment by monde** [comment]
Also, wanted to point out the v3 version of the Okta TF provider didn't have the recommended design principle of a TF resource concerning itself with a single api resource (e.g. an app shouldn't manage users and groups, there should be a resource to manage users and groups) https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles

**Comment by donmedlinger-cb** [comment]
I want to clarify. We are NOT assigning the users or groups through the `okta_app_saml` resource. We are defining those through the proper `okta_app_user` and `okta_app_group_assignment`. 

The issue we're having is that when terraform is doing the import during the plan, it is behind the scenes comparing the `okta_app_saml` attributes for users and groups, seeing those are not defined in the file and dropping the users.

That being said, I do not think we are on the latest and greatest version of the provider.

**Comment by duytiennguyen-okta** [comment]
@donmedlinger-cb could you show us your tf script?

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-651867
