### ISSUE TITLE
Terraform Plans Getting Stuck on Version 3.6.0

### ISSUE THREAD

**Issue by PurrBiscuit** [okta/terraform-provider-okta#214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.12.29
+ provider.okta v3.6.0
```

### Affected Resource(s)

This issue isn't related to one specific resource.  It's centered around a single repo that's managing a lot of Okta resources.

### Debug Output

There's a lot of PII in the `debug.log` file that I generated while troubleshooting this issue that I don't want to include in this public issue.  I'd be happy to email it directly to whoever is going to take a look into this issue, however.

### Expected Behavior

Given the large number of Okta resources we are managing in this one repo, it's not unusual for us to encounter `429 Too Many Request` errors during the refresh portion of the `terraform plan`.  Prior to version `3.6.0` of this provider, those `429` errors were handled and retried later.  That doesn't seem to be the case anymore with version `3.6.0` after upgrading the Okta SDK the provider is using to vesion `2.0.0`.

### Actual Behavior

Our `terraform plan` never successfully completes on that repo anymore.  It will hang indefinitely and never output an error.  We have to `Ctrl + C` to stop the plan, otherwise it will remain in the `plan` indefinitely without exiting on it's own.  Looking at the debug logs we see the expected `429` errors but no attempts to retry the resource.  We also see `*terraform.EvalSequence, err: Could not parse SAML app metadata, error: EOF` errors throughout the `debug.log` file after the `429` errors are encountered.  We've pinned that repo to use version `3.5.1` of this provider for now and that works fine.

### Steps to Reproduce

1. Create a repo that manages a lot of resources - it looks like it's specific to `app` type resources where the rate limit is lower on Okta.
2. Run a `TF_LOG=debug terraform plan` and see the `429` errors returned from the API.
3. Observe the `terraform plan` remaining stuck indefinitely.
4. Extra step - pin the provider to version `3.5.1` and run `terraform plan` again on the same repo; plan should complete successfully.

**Comment by PurrBiscuit** [comment]
Seems similar to this issue -> https://github.com/oktadeveloper/terraform-provider-okta/issues/210

**Comment by tgoodsell-tempus** [comment]
Here is the docs from the SDK where they describe how to use the re-try options: https://github.com/okta/okta-sdk-golang#connection-retry--rate-limiting

**Comment by tgoodsell-tempus** [comment]
Link to relevant usage in SDK: https://github.com/okta/okta-sdk-golang/blob/52c559514937dc072dc3212388bea2f8b968b641/okta/requestExecutor.go#L226

**Comment by bogdanprodan-okta** [comment]
Hi @PurrBiscuit, @tgoodsell-tempus! We are aware of this issue and there is already a PR to fix that. Once it will be merged and a new version of SDK will be rolled out, I will update providers modules, so the new version will no longer have this issue.

**Comment by bogdanprodan-okta** [comment]
Hi @PurrBiscuit @tgoodsell-tempus ! Today we released the new version v3.6.1. In case this issue is no longer exists, please close it. Thanks!

**Comment by PurrBiscuit** [comment]
Thanks for work on this - will close this issue out. 👍

**Comment by isometry** [comment]
We are still seeing this issue manifest with v3.6.1…
@PurrBiscuit : did v3.6.1 actually resolve the issue for you?

**Comment by PurrBiscuit** [comment]
@isometry yes, you're correct - this is still an issue.  I still had our repo pinned to version `3.5.1` so it wasn't pulling `3.6.1` in the test I ran.  I'm still seeing the rate limit errors and hanging Terraform plans on our larger repos with version `3.6.1`.  Will reopen this issue.

**Comment by bogdanprodan-okta** [comment]
Hi everyone! This is still a rate-limiting issue for big terraform plans, but there is #187 PR which should fix this issue to avoid long periods of sleep during the `apply` process. There is also a plan to add logs to all the resources so it's clearer what is going on. In v3.7.0 a `log_level` option was introduced (`error` is the default one), so now it's possible to adjust the log level. Some of the resources already have logs indicating create, update, and delete actions. Hopefully, the new version (3.7.1 or 3.8.0) will have logs available for all the resources.
