### ISSUE TITLE
Missing binaries for the 3.11.0 release

### ISSUE THREAD

**Issue by adamcrews** [okta/terraform-provider-okta#480]
Are there any update on getting 3.11.0 published to the terraform registry?  It has been a bit and all the tickets that reference this work have been closed.

Also, I am pretty sure that a only few days ago, the 3.11.0 release published on github had binaries built available, but those seem to have disappeared, and there is only the source zip and tgz on the releases page.    Is it possible to get the binaries (re?)published for 3.11.0 on github?

**Comment by bogdanprodan-okta** [comment]
Hi @adamcrews! Yes, I will republish these binaries shortly. In addition, Hashicorp has finally solved their issue with gpg key, so there will be probably a v4.0.0 release next month into the new `okta` namespace. The reason for that is there are a lot of deprecated resources in the current version and also there will be some changes in the config files to support multiple organizations.

**Comment by tgoodsell-tempus** [comment]
@bogdanprodan-okta would y'all also publish these the pre-4.0 releases in the new namespace as well? That way we can do a bit of a gentler upgrade, between the breaking change and having to update the provider location.

**Comment by bogdanprodan-okta** [comment]
@tgoodsell-tempus yes, it's going to be published into the new namespace.

**Comment by tgoodsell-tempus** [comment]
@bogdanprodan-okta  Just a FYI, since I saw some of the releases run.

Looks like `oktadeveloper/okta` got `3.11` published to it, but I think it wasn't fully taken in since I got this error from an init using the provider:

```
╷

│ Error: Incompatible provider version

│ 

│ Provider registry.terraform.io/oktadeveloper/okta v3.11.0 does not have a

│ package available for your current platform, linux_amd64.

│ 

│ Provider releases are separate from Terraform CLI releases, so not all

│ providers are available for all platforms. Other versions of this provider

│ may have different platforms supported.

╵
```

**Comment by daegalus** [comment]
I am having the same error currently. Issues with missing linux_amd64 packages.

**Comment by ChristophShyper** [comment]
@bogdanprodan-okta please let us know when it's fixed. 
All Okta integrations broke over the weekend with this new release. 
At least `3.10.1` still works.

**Comment by dsalaza4** [comment]
We're getting the `Error: Failed to install provider
Error while installing oktadeveloper/okta v3.11.0: provider
registry.terraform.io/oktadeveloper/okta 3.11.0 is not available for
linux_amd64` as well.

**Comment by bogdanprodan-okta** [comment]
Hi everyone! Currently, I'm waiting for a response from Hashicorp.

**Comment by joe-a-t** [comment]
@bogdanprodan-okta Is it possible to remove the `3.11.0` release entirely so that unpinned providers will go back to using `3.10.1`? If people can't initialize `3.11.0`, it seems like having it exist in the world is just causing issues. Then whenever the relevant stuff with Hashicorp is fixed, it can be re-published.

**Comment by bogdanprodan-okta** [comment]
Hello everyone! Finally, Okta provider is published [under the new namespace](https://registry.terraform.io/providers/okta/okta/latest)!!! Here an example of how to use it:
```
required_providers {
    okta = {
      source = "okta/okta"
      version = "3.11.0"
    }
  }
```
Note here, that no new versions gonna be published into the `oktadeveloper` namespace.

**Comment by ChristophShyper** [comment]
@bogdanprodan-okta Sorry, but the error still remains:
```
Initializing provider plugins...
- Finding okta/okta versions matching "~> 3.0"...
- Finding latest version of oktadeveloper/okta...
- Installing okta/okta v3.11.0...
- Installed okta/okta v3.11.0 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Error: Incompatible provider version

Provider registry.terraform.io/oktadeveloper/okta v3.11.0 does not have a
package available for your current platform, linux_amd64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

**Comment by synepolskyi** [comment]
Agree with Christoph, I have the same error. In my case, it's related to the current state:
```
$ terraform providers

Providers required by state:

    provider[registry.terraform.io/oktadeveloper/okta]
```

So provider update from `oktadeveloper/okta:<any-version>` to `okta/okta:3.11.0` is not possible without manipulations with state.

**Comment by cvs-sigrejas** [comment]
I don't think this is working yet.
```
% terraform init

Initializing the backend...

Initializing provider plugins...
- Finding okta/okta versions matching "3.11.0"...
╷
│ Error: Failed to install provider
│ 
│ Error while installing okta/okta v3.11.0: could not query provider registry for registry.terraform.io/okta/okta: failed to retrieve authentication
│ checksums for provider: 404 Not Found
```

**Comment by cvs-sigrejas** [comment]
The good news is that you can use `3.10.0` with the new namespace and it'll work.
```
terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "3.10.0"
    }
  }
}
```

Init
```
Initializing provider plugins...
- Finding okta/okta versions matching "3.10.0"...
- Installing okta/okta v3.10.0...
- Installed okta/okta v3.10.0 (signed by a HashiCorp partner, key ID 7F89989587DEEA62)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by cvs-sigrejas** [comment]
`3.11.0` does not work, but `3.11.1` does work!

**Comment by bogdanprodan-okta** [comment]
Hi everyone! Sorry for the mess! I've released new v3.11.1, which is similar to v3.11.0 (the only difference is I've used the 1.16 version of the Gloang instead of 1.14 to build the binaries). Could you try to init terraform with this version?

I've also asked Hashicorp to add old `gpg` key to the registry, so all the oldest versions are valid.

**Comment by ChristophShyper** [comment]
I still have an error:
```
Initializing provider plugins...
- Finding okta/okta versions matching "~> 3.0"...
- Finding latest version of oktadeveloper/okta...
- Installing okta/okta v3.11.1...
- Installed okta/okta v3.11.1 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Error: Incompatible provider version

Provider registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a
package available for your current platform, linux_amd64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

I'm using dockerized Alpine 3.13 as a base system and MacOS Catalina as host.

**Comment by bogdanprodan-okta** [comment]
> I still have an error:
> 
> ```
> Initializing provider plugins...
> - Finding okta/okta versions matching "~> 3.0"...
> - Finding latest version of oktadeveloper/okta...
> - Installing okta/okta v3.11.1...
> - Installed okta/okta v3.11.1 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)
> 
> Partner and community providers are signed by their developers.
> If you'd like to know more about provider signing, you can read about it here:
> https://www.terraform.io/docs/cli/plugins/signing.html
> 
> Error: Incompatible provider version
> 
> Provider registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a
> package available for your current platform, linux_amd64.
> 
> Provider releases are separate from Terraform CLI releases, so not all
> providers are available for all platforms. Other versions of this provider may
> have different platforms supported.
> ```
> 
> I'm using dockerized Alpine 3.13 as a base system and MacOS Catalina as host.

If you having a problem similar to this, go to your state file and replace all the occurrences of `oktadeveloper` to `okta`. This should help.

**Comment by ChristophShyper** [comment]
> If you having a problem similar to this, go to your state file and replace all the occurrences of `oktadeveloper` to `okta`. This should help.

OK, that helped, thanks. 
Strange that when Cloudflare provider changed namespace this wasn't necessary. 
Terraform is so inconsistent... Why have separate config for providers when all is hardcoded in state file either way...

**Comment by tgoodsell-tempus** [comment]
For anyone seeing this, you probably will need to use https://www.terraform.io/docs/cli/commands/state/replace-provider.html to fix the state manually.

You are supposed to be able to switch provider sources OK, however if you don't have a local plugin cache with a working version installed, then it'll try to DL the `3.11.x` (latest) version of `oktadeveloper/okta` which does not work.

**Comment by joe-a-t** [comment]
If people are looking for an easy way to switch all references from `oktadeveloper/okta` to `okta/okta`, you can use [this script](https://github.com/joeaawad/random-scripts/blob/master/update-repos.py) to change all references in a specified repo (`--repo-regex`) or all repos with a given topic (`--repo-topic`). Add `--pr` to the below command to generate pull requests with the changes.

```sh
python update-repos.py --org-name="foo" --branch-name="okta-provider" --commit-message="replace okta provider" --target="oktadeveloper/okta" --replacement="okta/okta" --repo-regex="foo"
```

**Comment by jluk-box** [comment]
@bogdanprodan-okta Hi, could you add some information about the move to `okta` namespace in the `oktadeveloper` org description (https://registry.terraform.io/namespaces/oktadeveloper)? It can help find the cause and solution faster for people with broken deployments.

**Comment by thiagocaiubi** [comment]
> > I still have an error:
> > ```
> > Initializing provider plugins...
> > - Finding okta/okta versions matching "~> 3.0"...
> > - Finding latest version of oktadeveloper/okta...
> > - Installing okta/okta v3.11.1...
> > - Installed okta/okta v3.11.1 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)
> > 
> > Partner and community providers are signed by their developers.
> > If you'd like to know more about provider signing, you can read about it here:
> > https://www.terraform.io/docs/cli/plugins/signing.html
> > 
> > Error: Incompatible provider version
> > 
> > Provider registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a
> > package available for your current platform, linux_amd64.
> > 
> > Provider releases are separate from Terraform CLI releases, so not all
> > providers are available for all platforms. Other versions of this provider may
> > have different platforms supported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm using dockerized Alpine 3.13 as a base system and MacOS Catalina as host.
> 
> If you having a problem similar to this, go to your state file and replace all the occurrences of `oktadeveloper` to `okta`. This should help.

I was facing the same issue after changing from oktadeveloper/okta to okta/okta in terraform configuration files. Replace provider in the state file fixed it:

```
terraform state replace-provider oktadeveloper/okta okta/okta
```

**Comment by bogdanprodan-okta** [comment]
Since this is no longer an issue, I'm closing this. Big thanks to everyone for the valuable comments!!
