### ISSUE TITLE
skip_users = true is not respected for okta_app_oauth, queries all groups/users anyway

### ISSUE THREAD

**Issue by kensykora** [okta/terraform-provider-okta#884]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/anschoewe/curl v0.1.3
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
+ provider registry.terraform.io/hashicorp/external v2.1.1
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "load_test" {
  label               = "Load Test"
  type                = "native"
  grant_types         = ["password", "authorization_code"]
  redirect_uris       = ["https://localhost:50011/"]
  response_types      = ["code"]
  issuer_mode         = "CUSTOM_URL"
  implicit_assignment = true
  consent_method      = "REQUIRED"

  skip_groups = true
  skip_users = true
}
```

### Debug Output

I have a private gist, please contact me if you need the logs

### Steps to Reproduce

0. Precondition: Have an existing okta app
1. Create an `okta_app_oauth` resource in a .tf file that maps to an existing okta app
2. Import the existing app `terraform import okta_app_oauth.load_test <app id>`
3. Run `terraform plan`

### Expected Behavior

After importing an existing app, setting `skip_groups = true` and `skip_users = true` should be respected when running terraform plan and apply operations.

### Actual Behavior

All users and groups associated with the app are queried. In our use case, we have a load test that keeps 50k users in Okta and each and every one of these users is queried in the API, which triggers rate limit warnings and slows down our okta instance.

### References

Related:

- #652 
- #595 
- #585 
- #572

**Comment by kensykora** [comment]
Workaround: as suggested in #652:

1. `terraform state pull > state.json`
2. Increment `serial` property
3. find all usages of `skip_users` and `skip_groups` and set their values to `true`
4. `terraform state push state.json`

**Comment by mvitt** [comment]
This still seems to be happening. Can this be reopened please?

**Comment by monde** [comment]
@mvitt we can reopen this issue. Can you give me a sample of your Terraform config and a description of your context (number of users, number of app, number of groups, etc.). What version of the provider are you using.

**Comment by monde** [comment]
Closing this one again, skip seems to be working well now, please reopen if this is not the case. We started talking about this again on v3.27.0 and we've just released v3.30.0

**Comment by carl-adams-planet** [comment]
I believe this still happens on application import.   Using TF provider version v 3.44, importing an okta_app_oauth app with skip_users and skip_groups set to true still results in an enormous number of calls as it enumerates every user assigned the app.
